from .attendance import *
from .course import *
from .language import *
from .lesson import *
from .link import *
from .picture import *
from .role import *
from .solve import *
from .task import *
from .tasktype import *
from .user import *
